server:
  port: 8091
spring:
  application:
    name: config-server-demo
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/gloriainga/config-server-tarea.git
          username: 
          password: 
          default-label: main
  profiles:
    active: git